### ISSUE TITLE
Bypass Numpy Version Check

### ISSUE THREAD

**Issue by defencedog** [fedebenelli/PyForFluids#27]
Technically I am on an ARM64 where compiling numpy is an headache. I already have fully functional `SCIPY, NUMPY, SYMPY` & many others!
Currently I have numpy `1.20.3' so how I modify some file in source so that it bypass numpy version check

**Comment by fedebenelli** [comment]
You could disable the checks on the pyproject.toml and setup.py files (see that the version is forced in both of those files)

I haven't tested this package on an ARM machine so I would love if you could keep me informed on this!

**Comment by defencedog** [comment]
@fedebenelli Why the setup is building numpy when its already there

```
pip list | grep -e numpy -e scipy -e setuptool -e wheel
numpy                 1.23.4
scipy                 1.8.0
setuptools            58.1.0
wheel                 0.37.1
[install.log.txt](https://github.com/fedebenelli/PyForFluids/files/9948717/install.log.txt)

```

**Comment by defencedog** [comment]
**SUCCESSFUL**
@fedebenelli 
First edited already installed package versions so wheel building is easy! But it shouldn't re-build `numpy` provided its already installed
Edited pyproject.toml `requires = ["setuptools==58.1.0", "wheel==0.37.1", "numpy==1.23.4"]`
& setup.py `REQUIREMENTS = ["numpy==1.23.4", "pandas==1.4.4", "scipy==1.8.0"]`

then issued `MATHLIB=m python3.9 -m pip  install -v . 2>&1 | tee install.log`

[install.log.txt](https://github.com/fedebenelli/PyForFluids/files/9950873/install.log.txt)
