### ISSUE TITLE
pff.equilibrium.flash_pt()

### ISSUE THREAD

**Issue by PetroleumEngineer** [fedebenelli/PyForFluids#32]
flash_pt = pff.equilibrium.flash_pt()

composition = {'propane': 0.01, 'butane': 0.5, 'isobutane': 0.15, 
               'pentane': 0.2, 'hexane': 0.14}
temperature = 366.48
pressure = 1.039e6

fluid = pff.Fluid(
    model=pff.models.GERG2008(),
    composition=composition,
    temperature=temperature,
    density=1,
)

vapor, liquid, beta, it = flash_pt(fluid, pressure, temperature)

above: code form tutorial

below is error:
AttributeError                            Traceback (most recent call last)
Cell In[82], [line 1](vscode-notebook-cell:?execution_count=82&line=1)
----> [1](vscode-notebook-cell:?execution_count=82&line=1) flash_pt = pff.equilibrium.flash_pt()
      [3](vscode-notebook-cell:?execution_count=82&line=3) composition = {'propane': 0.01, 'butane': 0.5, 'isobutane': 0.15, 
      [4](vscode-notebook-cell:?execution_count=82&line=4)                'pentane': 0.2, 'hexane': 0.14}
      [5](vscode-notebook-cell:?execution_count=82&line=5) temperature = 366.48

AttributeError: module 'pyforfluids' has no attribute 'equilibrium'

Question:,  did you guys moved it to somewhere??

**Comment by PetroleumEngineer** [comment]
I created clone and made (SM_subbrunch), Now, I am running it  from my Mac. and I got the same error.
Did I do something wrong ? 
<img width="1093" alt="Screenshot 2024-01-18 at 11 59 52" src="https://github.com/fedebenelli/PyForFluids/assets/86235779/61cbf948-0fb1-4e21-9948-035efea5dd43">

**Comment by fedebenelli** [comment]
Hmm... that's pretty odd

Could you try importing `equilibrium` separately? 

`import pyforfluids.equilibrium`

or

`from pyforfluids.equilibrium import flash_pt`

**Comment by PetroleumEngineer** [comment]
yes, I have tried that, still having the same issue. Do not understand what causes it.
![Uploading Screenshot 2024-01-19 at 09.58.32.png…]()

**Comment by PetroleumEngineer** [comment]
Yes I tried it few time and still no success. I can't understand what exactly causes it.
<img width="831" alt="Screenshot 2024-01-19 at 09 58 32" src="https://github.com/fedebenelli/PyForFluids/assets/86235779/ef7294fb-1107-40f4-b3d6-cb8f502a3ba8">

**Comment by PetroleumEngineer** [comment]
reopen

**Comment by PetroleumEngineer** [comment]
I think i might know what can cause this issue but i do not know how to resolve it.
i have installed pyforfluids with command (pip install pyforfluids). maybe when ever i call equilibrium funciton, it tries to us public version (which you said doesn't have PT).

**Comment by fedebenelli** [comment]
Yeah, that's the problem. You have to install the version that you've cloned, to do that you must do

> `pip install .` 

Inside the cloned directory

**Comment by fedebenelli** [comment]
Out of curiosity, what are your expectations with this library? We're in a process of big redesign and are curious about different interest from the user's perspective

**Comment by PetroleumEngineer** [comment]
I am working on a project where i need thermodynamic properties of CO2, and it's mixture with H2O.
I like working a lot on visualizations with plotly.I will make few nice functions for better parameter representation and share with you later on.

I wanted to check with you about something, i want to make sure i understood some parameter's units correctly.
whenever i define density range f.i : density_range = np.linspace(1e-5, 8, 100) 
density will be given in mol/dm^3 ? which also equal to mol/L
will it be okay in this case just multiply it by molecular weight of CO2 (44.01 gr/mol) to get kg/m^3?

![image](https://github.com/fedebenelli/PyForFluids/assets/86235779/0fd6890a-1ef8-472e-b96d-9a36e2fc2a58)

**Comment by fedebenelli** [comment]
Yes, that conversion would be correct since you're converting from:

- mol/dm^3 -> 1000 dm^3/m^3 mol/dm^3 

and

- 1000 mol/m^3 -> g/mol 1Kg/1000g 

So both `1000` get cancelled together

**Comment by PetroleumEngineer** [comment]
Could you please share some information about units, for example, 'second_thermal_virial_coeff'
